export type EmployeeRole = 'EMPLOYEE' | 'SUPERVISOR' | 'ADMIN' | 'SUPER_ADMIN' | 'CLIENT';
export type EmployeeStatus = 'ACTIVE' | 'INACTIVE' | 'ON_LEAVE' | 'TERMINATED';

export interface Employee {
  id: string;
  employeeId?: string;
  fullName: string;
  email?: string;
  phone: string;
  role: EmployeeRole;
  status: EmployeeStatus;
  siteName?: string;
  siteId?: string;
  joiningDate: string;
  enrollmentDate?: string;
  gender?: string;
  dob?: string;
  dateOfBirth?: string;
  bankName?: string;
  bankAccountNumber?: string;
  bankIfscCode?: string;
  pfNumber?: string;
  uanNumber?: string;
  esicNumber?: string;
  hasFaceRegistered?: boolean;
  documents?: any[];
  employeeExternalId?: string;
  designation?: string;
  department?: string;
  linNumber?: string;
  maritalStatus?: string;
  bloodGroup?: string;
  heightFeet?: number;
  heightInches?: number;
  weightKg?: number;
  education?: string;
  languagesKnown?: string;
  emergencyContactNumber?: string;
  policeVerificationStatus?: boolean;
  form11Number?: string;
  residentialProofStatus?: boolean;
  residentialAddress?: string;
  termsAndConditionsAccepted?: boolean;
  aadhaar?: string;
  pan?: string;
}
